#+STARTUP: showall

* Changelog

** 0.2.1

- ~Fixed~ Vertical Space when segments get truncated. Just added vertical space in the default segments accordingly.

** 0.2.0

- ~Fixed~ Fixed tests and fixed linting errors.
- ~Changed~ Simplified ~...--get-symbol~, gets called with variable name directly now, now need for ~intern-soft~.
- ~Changed~ ~...--vc-branch-get~ was brittle if for some reason the ~vc-mode~ would not be of the right length.
- ~Changed~ Some little optimizations and fixes.
- ~Changed~ ~winum-auto-setup-modeline~ is disabled when activating the modeline instead of each time the segment ist recalculated (inefficient).
- ~Fixed~ If the text in the modeline is too long, it gets truncated and tries to be sort of intelligent. For this I added a new segment ~:left-important~. This segment has the highest priority and is truncated in the very end if needed. ~:left~ ist the first segment to be truncated if needed followed by ~:right~.
- ~Added~ If the scroll bar is enabled it is also taken into account when calculating the alignment of the right segment.
- =Fixed= Aligning with ~fringes-outside-margins~ set to ~nil~ was not working correctly.
- =Changed= Snapshot Emacs version using continue-on-error: true now.
- =Added= Line and column number segments.
- =Fixed= Aligning to the right is now pixel perfect.
- =Added= Test for ~lordar-mode-line-segments--buffer-name-invalidate-cache~.

** Remark

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/), and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

Type of changes:

- =Added= for new features.
- =Changed= for changes in existing functionality.
- =Deprecated= for soon-to-be removed features.
- =Removed= for now removed features.
- =Fixed= for any bug fixes.
- =Security= in case of vulnerabilities.
