#+STARTUP: showall
* Contributing

** Bugs, Improvements and new Features

Go to issues page and make a new issue.

Make sure to:

- Check that the issue has not already been reported (open and closed issues).
- Check that the issue is not part of an active pull request.

** Pull Requests

Cool that you want to contribute your code :-)

Remember to:

- Include only one feature in a pull request.
- Open an issue and mention your planned pull request.
- Add/update tests if needed.
- The tests must pass (see [[#testing][Testing]]).
- Update [[./README.org][README.org]] if needed.
- Update the documentation in the [[./README.org][README.org]] if needed.
- Update [[./CHANGELOG.org][CHANGELOG.org]].

*** Testing
:PROPERTIES:
:CUSTOM_ID: testing
:END:

Uses [[https://emacs-eask.github.io/Getting-Started/Introduction/][Eask]]  which needs to be [[https://emacs-eask.github.io/Getting-Started/Install-Eask/#-npm-cross-platform][installed]]. The tests are written with [[https://github.com/jorgenschaefer/emacs-buttercup][Buttercup]]. After pushing to GitHub an action is triggered which calls =make all=.

**** Testing locally

To test the package locally call the Makefile targets or :

| Target         | Description                                       |
|----------------+---------------------------------------------------|
| make           | Show help for targets available                   |
| make all       | Build & install package, compile, test and lint   |
| make clean     | Clean everything                                  |
| make package   | Build package artifact                            |
| make install   | Install the package                               |
| make compile   | Compiles the files to check for errors/warnings   |
| make test      | Run tests with buttercup                          |
| make lint      | Clean autoloads and run linters                   |
| make emacs     | Run Emacs with package and dependencies installed |

***** Linters

By default (=make lint=) the following linters are used: package-lint, checkdoc, indent-lint, relint. If you want to use another linter or call a linter separately use =eask lint=.

***** Run Specific Emacs Version in Docker Container

It is possible to run an Eask command with specific Emacs version in a docker container:

#+BEGIN_SRC shell
  # Run the test with Emacs version 29.4
  eask docker 29.4 test buttercup
#+END_SRC

- Unfortunately I have not found a way to run the make targets (tried =eask docker 29.4 exec make test=). 
- =eask docker 29.4 emacs= doesn't seem to work. I was able to launch an Emacs with the following command:

  #+BEGIN_SRC shell
    docker run --interactive --tty \
        --volume ~/projects/coding/lordar-mode-line:/lordar-mode-line \
        --workdir /lordar-mode-line \
        --rm \
        silex/emacs:29.4-ci-eask emacs \
        --init-directory /lordar-mode-line/.eask/29.4
  #+END_SRC


